ARG img_version
FROM godot-fedora:${img_version}

RUN dnf -y install --setopt=install_weak_deps=False \
      xorg-x11-server-Xvfb libXcursor libXinerama libXrandr libXi \
      alsa-lib pulseaudio-libs mesa-dri-drivers java-11-openjdk-devel

CMD /bin/bash
