ARG img_version
FROM godot-fedora:${img_version}

ENV EMSCRIPTEN_VERSION=4.0.10

RUN dnf -y install --setopt=install_weak_deps=False libatomic && \
    git clone --branch ${EMSCRIPTEN_VERSION} --progress https://github.com/emscripten-core/emsdk && \
    emsdk/emsdk install ${EMSCRIPTEN_VERSION} && \
    emsdk/emsdk activate ${EMSCRIPTEN_VERSION}

CMD /bin/bash
