ARG img_version
FROM godot-osx:${img_version}

RUN dnf -y install --setopt=install_weak_deps=False \
      automake autoconf gcc gcc-c++ gcc-objc gcc-objc++ cmake libicu-devel libtool libxml2-devel openssl-devel perl python yasm

RUN git clone --depth 1 --no-checkout https://github.com/tpoechtrager/cctools-port.git && \
    cd /root/cctools-port && \
    git fetch --depth 1 origin 1cce4a06877992f708b2e0e2ab217a0cfb923a4f && \
    git checkout 1cce4a06877992f708b2e0e2ab217a0cfb923a4f

COPY files/appleembedded/build.sh /root/cctools-port/usage_examples/ios_toolchain/build.sh
COPY files/appleembedded/wrapper.c /root/cctools-port/usage_examples/ios_toolchain/wrapper.c

RUN chmod +x /root/cctools-port/usage_examples/ios_toolchain/build.sh

RUN cd /root/cctools-port && \
    usage_examples/ios_toolchain/build.sh arm64 && \
    mkdir -p /root/ioscross/arm64 && \
    mv usage_examples/ios_toolchain/target/* /root/ioscross/arm64 && \
    mkdir /root/ioscross/arm64/usr && \
    ln -s /root/ioscross/arm64/bin /root/ioscross/arm64/usr/bin

RUN cd /root/cctools-port && \
    usage_examples/ios_toolchain/build.sh x86_64 && \
    mkdir -p /root/ioscross/x86_64 && \
    mv usage_examples/ios_toolchain/target/* /root/ioscross/x86_64 && \
    mkdir /root/ioscross/x86_64/usr && \
    ln -s /root/ioscross/x86_64/bin /root/ioscross/x86_64/usr/bin

RUN PATH=/root/ioscross/arm64/bin:$PATH /root/files/appleembedded/check-arm.sh

ENV OSXCROSS_IOS=not_nothing
ENV OSXCROSS_TVOS=not_nothing
ENV OSXCROSS_VISIONOS=not_nothing
ENV OSXCROSS_APPLEEMBEDDED=not_nothing

ENV PATH="/root/ioscross/arm64/bin:/root/ioscross/x86_64/bin:${PATH}"

# Patch the visionOS SDK in place so it can be consumed by the swift.org
# 6.3 release compiler. See files/appleembedded/patch-visionos-sdk.sh for
# the per-category rationale and upstream-fix pointers.
COPY files/appleembedded/patch-visionos-sdk.sh /root/patch-visionos-sdk.sh
RUN chmod +x /root/patch-visionos-sdk.sh && \
    . "${SWIFTLY_HOME_DIR:-$HOME/.local/share/swiftly}/env.sh" && \
    /root/patch-visionos-sdk.sh && \
    rm /root/patch-visionos-sdk.sh

CMD /bin/bash
